### ISSUE TITLE
Evidence markers

### ISSUE THREAD

**Issue by dosumis** [Cellular-Semantics/whole_mouse_brain_taxonomy#1]
I noticed that the evidence marker columns is filled

e.g. 

<img width="1448" alt="image" src="https://github.com/Cellular-Semantics/whole_mouse_brain_taxonomy/assets/112839/e39c46e9-7a01-4714-bf2b-6a50c29b8fe3">

AFAIK there are no evidence markers for this taxonomy.  Do these come from NS-Forest?.  If so, I think they need a new slot.  I would remove for now until we have a slot in the schema for them, or make them an 'author' field.

**Comment by hkir-dev** [comment]
Evidence markers are coming from `cluster.markers.combo`  `supertype.markers.combo`  and `subclass.markers.combo columns` of the supplementary materials (https://www.nature.com/articles/s41586-023-06812-z#Sec49 Table 7).

`marker_gene_evidence` column cleaned and existing markers moved to author annotation fields.
